services:
  backend:
    build: ./backend
    # Uncomment to use pre-built image from GitHub Container Registry
    # image: ghcr.io/USERNAME/REPO/backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./scripts:/app/scripts
    env_file:
      - ./backend/.env
    # For local development, you can override the JWT secret here
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-local-development-key}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

  frontend:
    build: ./frontend
    # Uncomment to use pre-built image from GitHub Container Registry
    # image: ghcr.io/USERNAME/REPO/frontend:latest
    ports:
      - "3001:3000"
    environment:
      # Frontend runs in browser, so we need to use localhost
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: tour-manager
