version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-development-key}
      - DOCKER_ENV=true
      - DATABASE_PATH=/app/data/tourmanager.db
      # Email configuration for Firestorm.ch
      - MAIL_SERVER=${MAIL_SERVER:-smtp.maildomain.ch}
      - MAIL_PORT=${MAIL_PORT:-465}
      - MAIL_USERNAME=${MAIL_USERNAME:-your-email@yourdomain.ch}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-your-password}
      - MAIL_FROM=${MAIL_FROM:-your-email@yourdomain.ch}
      - MAIL_STARTTLS=${MAIL_STARTTLS:-True}
      - MAIL_SSL_TLS=${MAIL_SSL_TLS:-False}
      - USE_CREDENTIALS=${USE_CREDENTIALS:-True}
      - FRONTEND_URL=http://localhost:3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: tour-manager
