services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./scripts:/app/scripts:ro
    environment:
      - DATABASE_PATH=/app/scripts/touren.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: tour-manager
