name: Build and Push Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create test environment files
      run: |
        # Create backend test environment
        echo "DATABASE_PATH=/app/scripts/touren.db" > backend/.env
        echo "JWT_SECRET_KEY=test-secret-key-for-ci" >> backend/.env
        echo "PORT=8000" >> backend/.env
        
        # Create frontend test environment
        echo "VITE_API_BASE_URL=http://localhost:8000" > frontend/.env

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm ci

    - name: Run backend tests
      working-directory: ./backend
      env:
        JWT_SECRET_KEY: test-secret-key-for-ci
        DATABASE_PATH: /app/scripts/touren.db
      run: |
        python -m pytest

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        npm run test

  build-and-push:
    needs: test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Custom Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REPOSITORY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Create .env file
      run: |
        echo "DATABASE_PATH=/app/scripts/touren.db" > backend/.env
        echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> backend/.env
        echo "PORT=8000" >> backend/.env

    - name: Build and push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.REPOSITORY }}/tourmbackend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.REPOSITORY }}/tourmui:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VITE_API_BASE_URL=https://rmbackend.bansom.synology.me
