name: Build and Push Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest pytest-env

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        # First install to update package-lock.json with new dependencies
        npm install
        # Then install all dependencies from the updated lock file
        npm install

    - name: Run backend tests
      working-directory: ./backend
      env:
        JWT_SECRET_KEY: test-secret-key-for-ci
        DATABASE_PATH: /app/scripts/touren.db
        PORT: "8000"
      run: |
        # Create test data directory if needed
        mkdir -p scripts
        touch scripts/touren.db
        python -m pytest -v

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        npm run test

  build-and-push:
    needs: test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Custom Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REPOSITORY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Setup build environment
      run: |
        # Create necessary directories
        mkdir -p backend/scripts
        touch backend/scripts/touren.db
        
        # Create environment file for build
        cat > backend/.env << EOL
        DATABASE_PATH=/app/scripts/touren.db
        JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
        PORT=8000
        EOL

    - name: Build and push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.REPOSITORY }}/tourmbackend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.REPOSITORY }}/tourmui:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VITE_API_BASE_URL=https://tourmbackend.bansom.synology.me
