name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BACKEND_IMAGE_NAME: tour-manager-backend
  FRONTEND_IMAGE_NAME: tour-manager-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract metadata for versioning
      - name: Extract metadata for Backend Image
        id: metabackend
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.BACKEND_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=short

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metabackend.outputs.tags }}
          labels: ${{ steps.metabackend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for Frontend Image
        id: metafrontend
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.FRONTEND_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=short

      # Build and push Frontend image
      - name: Build Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metafrontend.outputs.tags }}
          labels: ${{ steps.metafrontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Test the stack
      - name: Test Stack
        run: |
          docker compose up -d
          # Wait for services to be healthy
          timeout 30 bash -c 'until curl -s http://localhost:8000/ > /dev/null; do sleep 1; done'
          timeout 30 bash -c 'until curl -s http://localhost:3001/ > /dev/null; do sleep 1; done'
          # Run any additional tests here
          docker compose down
